name: gstsampleproject
description: This project is a mock application using MVVM design pattern. The whole purpose of this sample app is to check the user information and provide dynamic values. Implementing with the best practices

publish_to: 'none'

version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:    ^1.0.2   # IOS Icons

  provider:           ^6.0.0   # ViewModel - For Change Notifiers or 2Way Binding
  shared_preferences: ^2.0.7   # LocalStorage - On Device Storage
  http:               ^0.13.3  # Model - Http services provider

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages